log_region_pct:
  x: 0.2159
  y: 0.0428
  w: 0.2269
  h: 0.0517

# Full log box for CS2 instance checker — captures all visible lines
logbox_full_pct:
  x: 0.2159
  y: 0.0428
  w: 0.2269
  h: 0.0517

button_point_pct:
  x: 0.5775
  y: 0.385

kill_all_cs2_point_pct:
  x: 0.8054
  y: 0.713
 
panel:
  dir: "C:/Users/SinFermera2/Downloads/FSM_PANEL v.2.8.0"
  
  first_run:
    initial_wait_seconds: 10
    force_on_ocr_fail: true  # If OCR fails, run clicks anyway
    
    clicks:
      - { x_pct: 0.5932, y_pct: 0.7736, wait_s: 2.0 }  # Click 1
      - { x_pct: 0.5803, y_pct: 0.6471, wait_s: 2.0 }  # Click 2
      - { x_pct: 0.8469, y_pct: 0.7843, wait_s: 2.0 }  # Click 3


paths:
  memreduct_exe:
    - "C:/Program Files/Mem Reduct/MemReduct.exe"

  rdpclient_exe:
    - "C:/Users/Farmer7/Downloads/RDPClient/RDPClient/RDPClient.exe"

rdp:
  user1_point_pct:
    x: 0.1902
    y: 0.2754
  user2_point_pct:
    x: 0.2366
    y: 0.3300
  ui_wait_s: 5.0
  dialog_wait_s: 1.0    

rdp_windows:
  # Size for each RDP game window (SixFarmers15, SixFarmers16)
  width: 1616   # Width in pixels
  height: 939  # Height in pixels
  # Window search term
  title_search: "SinFermera"
  focus_interval_minutes: 15